export default [
  {
    id: 'plus',
    type: 'bar',
    fill: 'var(--success)',
    title: 'Положительное влияние',
    isTitleShow: false,
    isFullHeight: true,
  },
  {
    id: 'ost',
    type: 'bar',
    fill: 'var(--text_secondary)',
    title: 'Остаточная оценка',
    isTitleShow: false,
    isFullHeight: true,
  },
  {
    id: 'cur',
    type: 'bar',
    title: 'Текущая оценка',
    fill: 'var(--border)',
    isTitleShow: false,
    isFullHeight: true,
  },
  {
    id: 'risk',
    type: 'line',
    fill: 'var(--pink)',
    title: 'Риск аппетит',
    isTitleShow: true,
    isFullHeight: false,
  },
  {
    id: 'fact',
    type: 'bar',
    fill: 'var(--title)',
    title: 'Факт',
    isTitleShow: true,
    isFullHeight: false,
  },
];
